name: '@nadeemjazmawe/inno-setup-action-CLI'
description: This action generate setup/installer files using Inno Setup

author: '@NadeemJazmawe'

inputs:
  filepath:
    description: 'Path for ISS file'
    required: true

runs:
  using: 'composite'
  steps:
    - run: ${{ github.action_path }}\src\ISCC.exe ${{inputs.filepath}}
      shell: cmd
